# 工作流名称
name: Build Gopeed for Windows 7

# 工作流触发器
on:
  # 允许手动触发
  workflow_dispatch:
jobs:
  build:
    # 使用最新的 Ubuntu 虚拟机环境
    runs-on: ubuntu-latest

    steps:
      # 第 1 步：拉取 Gopeed 的源代码
      - name: Checkout Gopeed Source Code
        uses: actions/checkout@v4
        with:
          repository: GopeedLab/gopeed
          ref: main

      # 第 2 步：设置 Go 1.18 环境 (关键修改)
      # 使用 Go 1.18.10 以确保与 Windows 7 的最大兼容性
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.18.10'

      # 第 3 步：执行交叉编译
      # 目标：Windows 32位 (x86)，以确保在 Windows 7 上的最大兼容性
      - name: Build for Windows (x86) for Win7 Compatibility
        env:
          GOOS: windows
          GOARCH: 386
          CGO_ENABLED: 0
        run: |
          # 进入要编译的 main 包所在目录
          cd cmd/gopeed
          
          # 执行编译命令
          echo "Building Gopeed with Go 1.18.10..."
          go build -o gopeed.exe -trimpath -ldflags="-s -w" .
          echo "Build finished: gopeed.exe"
          ls -l gopeed.exe

      # 第 4 步：上传编译产物
      - name: Upload Gopeed Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: gopeed-windows-x86-for-win7-go1.18
          path: cmd/gopeed/gopeed.exe
